// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: api/complete.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inputs []string `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Count  int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Debug  bool     `protobuf:"varint,3,opt,name=debug,proto3" json:"debug,omitempty"`
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_complete_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_complete_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_api_complete_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteRequest) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *CompleteRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CompleteRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type CompleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input             string              `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Count             int32               `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Hashtags          []*HashTag          `protobuf:"bytes,3,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	Matches           []*AhoCorasickMatch `protobuf:"bytes,4,rep,name=matches,proto3" json:"matches,omitempty"`
	MatchDurationNs   int64               `protobuf:"varint,5,opt,name=match_duration_ns,json=matchDurationNs,proto3" json:"match_duration_ns,omitempty"`
	SuggestDurationNs int64               `protobuf:"varint,6,opt,name=suggest_duration_ns,json=suggestDurationNs,proto3" json:"suggest_duration_ns,omitempty"`
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_complete_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_complete_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_api_complete_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteResponse) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *CompleteResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CompleteResponse) GetHashtags() []*HashTag {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

func (x *CompleteResponse) GetMatches() []*AhoCorasickMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *CompleteResponse) GetMatchDurationNs() int64 {
	if x != nil {
		return x.MatchDurationNs
	}
	return 0
}

func (x *CompleteResponse) GetSuggestDurationNs() int64 {
	if x != nil {
		return x.SuggestDurationNs
	}
	return 0
}

type CompleteResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []*CompleteResponse `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *CompleteResponses) Reset() {
	*x = CompleteResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_complete_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponses) ProtoMessage() {}

func (x *CompleteResponses) ProtoReflect() protoreflect.Message {
	mi := &file_api_complete_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponses.ProtoReflect.Descriptor instead.
func (*CompleteResponses) Descriptor() ([]byte, []int) {
	return file_api_complete_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteResponses) GetResponse() []*CompleteResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type HashTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *HashTag) Reset() {
	*x = HashTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_complete_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashTag) ProtoMessage() {}

func (x *HashTag) ProtoReflect() protoreflect.Message {
	mi := &file_api_complete_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashTag.ProtoReflect.Descriptor instead.
func (*HashTag) Descriptor() ([]byte, []int) {
	return file_api_complete_proto_rawDescGZIP(), []int{3}
}

func (x *HashTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HashTag) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AhoCorasickMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos  int32  `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Word string `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *AhoCorasickMatch) Reset() {
	*x = AhoCorasickMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_complete_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AhoCorasickMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AhoCorasickMatch) ProtoMessage() {}

func (x *AhoCorasickMatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_complete_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AhoCorasickMatch.ProtoReflect.Descriptor instead.
func (*AhoCorasickMatch) Descriptor() ([]byte, []int) {
	return file_api_complete_proto_rawDescGZIP(), []int{4}
}

func (x *AhoCorasickMatch) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *AhoCorasickMatch) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

var File_api_complete_proto protoreflect.FileDescriptor

var file_api_complete_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x55,
	0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x64, 0x65, 0x62, 0x75, 0x67, 0x22, 0xff, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x68, 0x74, 0x61,
	0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x52, 0x08, 0x68, 0x61, 0x73,
	0x68, 0x74, 0x61, 0x67, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x2e, 0x41, 0x68, 0x6f, 0x43, 0x6f, 0x72, 0x61, 0x73, 0x69, 0x63, 0x6b, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x75, 0x67, 0x67, 0x65,
	0x73, 0x74, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x73, 0x22, 0x4b, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x68, 0x54, 0x61, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x10, 0x41, 0x68, 0x6f,
	0x43, 0x6f, 0x72, 0x61, 0x73, 0x69, 0x63, 0x6b, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x32, 0x50, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x44, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x73, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x6f, 0x62, 0x75, 0x53, 0x75, 0x6d, 0x69, 0x73, 0x75, 0x2f, 0x61,
	0x68, 0x6f, 0x2d, 0x63, 0x6f, 0x72, 0x61, 0x73, 0x69, 0x63, 0x6b, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_complete_proto_rawDescOnce sync.Once
	file_api_complete_proto_rawDescData = file_api_complete_proto_rawDesc
)

func file_api_complete_proto_rawDescGZIP() []byte {
	file_api_complete_proto_rawDescOnce.Do(func() {
		file_api_complete_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_complete_proto_rawDescData)
	})
	return file_api_complete_proto_rawDescData
}

var file_api_complete_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_complete_proto_goTypes = []interface{}{
	(*CompleteRequest)(nil),   // 0: complete.CompleteRequest
	(*CompleteResponse)(nil),  // 1: complete.CompleteResponse
	(*CompleteResponses)(nil), // 2: complete.CompleteResponses
	(*HashTag)(nil),           // 3: complete.HashTag
	(*AhoCorasickMatch)(nil),  // 4: complete.AhoCorasickMatch
}
var file_api_complete_proto_depIdxs = []int32{
	3, // 0: complete.CompleteResponse.hashtags:type_name -> complete.HashTag
	4, // 1: complete.CompleteResponse.matches:type_name -> complete.AhoCorasickMatch
	1, // 2: complete.CompleteResponses.response:type_name -> complete.CompleteResponse
	0, // 3: complete.Complete.Complete:input_type -> complete.CompleteRequest
	2, // 4: complete.Complete.Complete:output_type -> complete.CompleteResponses
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_complete_proto_init() }
func file_api_complete_proto_init() {
	if File_api_complete_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_complete_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_complete_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_complete_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_complete_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_complete_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AhoCorasickMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_complete_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_complete_proto_goTypes,
		DependencyIndexes: file_api_complete_proto_depIdxs,
		MessageInfos:      file_api_complete_proto_msgTypes,
	}.Build()
	File_api_complete_proto = out.File
	file_api_complete_proto_rawDesc = nil
	file_api_complete_proto_goTypes = nil
	file_api_complete_proto_depIdxs = nil
}
